import { Workout } from '../../reducers/workoutsReducer';
import { VERSION_ONE } from '../../helpers/constants';
import Image from '../../assets/images/active-adult-aerobics-206573.jpg';

const fullBodyPower: Workout = {
  id: 'full-body-power',
  name: 'Full Body Power',
  imageUrl: Image,
  version: VERSION_ONE,
  exerciseGroups: [
    {
      id: '81df4d60-3987-45fa-9504-f5242eb18544',
      name: 'Warm Up',
      exercises: [
        {
          id: 'stationary_bike',
          name: 'Stationary Bike',
          timerInSeconds: 300,
          restPeriodInSeconds: 60,
        },
        {
          id: 'lunges',
          name: 'Lunges',
          timerInSeconds: 60,
          restPeriodInSeconds: 30,
        },
      ],
    },
    {
      id: '7958db10-d0a1-474a-b8eb-e3d7ea92c1af',
      name: 'Exercises',
      exercises: [
        {
          id: 'back_squat',
          name: 'Back Squat',
          weightInKilos: 40,
          repsGoal: 5,
          repsAchieved: 5,
          autoIncrement: 2.5,
          restPeriodInSeconds: 90,
        },
        {
          id: 'back_squat',
          name: 'Back Squat',
          weightInKilos: 40,
          repsGoal: 5,
          repsAchieved: 5,
          autoIncrement: 2.5,
          restPeriodInSeconds: 90,
        },
        {
          id: 'back_squat',
          name: 'Back Squat',
          weightInKilos: 40,
          repsGoal: 5,
          repsAchieved: 5,
          autoIncrement: 2.5,
          restPeriodInSeconds: 90,
        },
        {
          id: 'dead_lift',
          name: 'Dead Lift',
          weightInKilos: 80,
          repsGoal: 5,
          repsAchieved: 5,
          autoIncrement: 0,
          restPeriodInSeconds: 90,
        },
        {
          id: 'dead_lift',
          name: 'Dead Lift',
          weightInKilos: 80,
          repsGoal: 5,
          repsAchieved: 5,
          autoIncrement: 0,
          restPeriodInSeconds: 90,
        },
        {
          id: 'dead_lift',
          name: 'Dead Lift',
          weightInKilos: 80,
          repsGoal: 5,
          repsAchieved: 5,
          autoIncrement: 0,
          restPeriodInSeconds: 90,
        },
        {
          id: 'chin_up',
          name: 'Chin Ups',
          weightInKilos: 0,
          repsGoal: 5,
          repsAchieved: 5,
          autoIncrement: 0,
          restPeriodInSeconds: 90,
        },
        {
          id: 'chin_up',
          name: 'Chin Ups',
          weightInKilos: 0,
          repsGoal: 5,
          repsAchieved: 5,
          autoIncrement: 0,
          restPeriodInSeconds: 90,
        },
        {
          id: 'chin_up',
          name: 'Chin Ups',
          weightInKilos: 0,
          repsGoal: 5,
          repsAchieved: 5,
          autoIncrement: 0,
          restPeriodInSeconds: 90,
        },
        {
          id: 'overhead_press',
          name: 'Overhead Press',
          weightInKilos: 30,
          repsGoal: 5,
          repsAchieved: 5,
          autoIncrement: 2.5,
          restPeriodInSeconds: 90,
        },
        {
          id: 'overhead_press',
          name: 'Overhead Press',
          weightInKilos: 30,
          repsGoal: 5,
          repsAchieved: 5,
          autoIncrement: 2.5,
          restPeriodInSeconds: 90,
        },
        {
          id: 'overhead_press',
          name: 'Overhead Press',
          weightInKilos: 30,
          repsGoal: 5,
          repsAchieved: 5,
          autoIncrement: 2.5,
          restPeriodInSeconds: 90,
        },
        {
          id: 'push_ups',
          name: 'Push Ups',
          weightInKilos: 0,
          repsGoal: 20,
          repsAchieved: 20,
          autoIncrement: 0,
          restPeriodInSeconds: 60,
        },
        {
          id: 'push_ups',
          name: 'Push Ups',
          weightInKilos: 0,
          repsGoal: 20,
          repsAchieved: 20,
          autoIncrement: 0,
          restPeriodInSeconds: 60,
        },
        {
          id: 'push_ups',
          name: 'Push Ups',
          weightInKilos: 0,
          repsGoal: 20,
          repsAchieved: 20,
          autoIncrement: 0,
          restPeriodInSeconds: 60,
        },
        {
          id: 'ring_rows',
          name: 'Ring Rows',
          weightInKilos: 0,
          repsGoal: 12,
          repsAchieved: 12,
          autoIncrement: 0,
          restPeriodInSeconds: 60,
        },
        {
          id: 'ring_rows',
          name: 'Ring Rows',
          weightInKilos: 0,
          repsGoal: 12,
          repsAchieved: 12,
          autoIncrement: 0,
          restPeriodInSeconds: 60,
        },
        {
          id: 'ring_rows',
          name: 'Ring Rows',
          weightInKilos: 0,
          repsGoal: 12,
          repsAchieved: 12,
          autoIncrement: 0,
          restPeriodInSeconds: 60,
        },
      ],
    },
  ],
};

export default fullBodyPower;
