import {
  WorkoutOutline, // eslint-disable-line no-unused-vars
} from '../../helpers/types';
import { VERSION_ONE } from '../../helpers/constants';
import Image from '../../assets/images/active-athlete-barbell-2261482.jpg';

const glutesAndGlory: WorkoutOutline = {
  id: 'glutes-and-glory',
  name: 'Glutes & Glory',
  imageUrl: Image,
  version: VERSION_ONE,
  exerciseGroups: [
    {
      id: 'compound_barbell_exercises',
      name: 'Compound Barbell Exercises',
      exercises: [
        {
          id: 'back_squat',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 60,
          restPeriodInSeconds: 30,
        },
        {
          id: 'back_squat',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 60,
          restPeriodInSeconds: 30,
        },
        {
          id: 'back_squat',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 60,
          restPeriodInSeconds: 30,
        },
        {
          id: 'back_squat',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 60,
          restPeriodInSeconds: 30,
        },
        {
          id: 'back_squat',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 60,
          restPeriodInSeconds: 30,
        },

        {
          id: 'dead_lift',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 60,
          restPeriodInSeconds: 30,
        },
        {
          id: 'dead_lift',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 60,
          restPeriodInSeconds: 30,
        },
        {
          id: 'dead_lift',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 60,
          restPeriodInSeconds: 30,
        },
        {
          id: 'dead_lift',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 60,
          restPeriodInSeconds: 30,
        },
        {
          id: 'dead_lift',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 60,
          restPeriodInSeconds: 30,
        },
      ],
    },
    {
      name: 'calves',
      id: 'calves',
      exercises: [
        {
          id: 'standing_calf_raises',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 30,
          restPeriodInSeconds: 30,
        },
        {
          id: 'standing_calf_raises',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 30,
          restPeriodInSeconds: 30,
        },
        {
          id: 'standing_calf_raises',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 30,
          restPeriodInSeconds: 30,
        },
        {
          id: 'standing_calf_raises',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 30,
          restPeriodInSeconds: 30,
        },
        {
          id: 'standing_calf_raises',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 30,
          restPeriodInSeconds: 30,
        },

        {
          id: 'calf_press_on_leg_press',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 30,
          restPeriodInSeconds: 30,
        },
        {
          id: 'calf_press_on_leg_press',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 30,
          restPeriodInSeconds: 30,
        },
        {
          id: 'calf_press_on_leg_press',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 30,
          restPeriodInSeconds: 30,
        },
        {
          id: 'calf_press_on_leg_press',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 30,
          restPeriodInSeconds: 30,
        },
        {
          id: 'calf_press_on_leg_press',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 30,
          restPeriodInSeconds: 30,
        },
      ],
    },

    {
      id: 'quads_and_hamstrings',
      name: 'Quads and Hamstrings',
      exercises: [
        {
          id: 'leg_press',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 60,
          restPeriodInSeconds: 30,
        },
        {
          id: 'leg_press',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 60,
          restPeriodInSeconds: 30,
        },
        {
          id: 'leg_press',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 60,
          restPeriodInSeconds: 30,
        },
        {
          id: 'leg_press',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 60,
          restPeriodInSeconds: 30,
        },
        {
          id: 'leg_press',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 60,
          restPeriodInSeconds: 30,
        },

        {
          id: 'lying_leg_curls',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 30,
          restPeriodInSeconds: 30,
        },
        {
          id: 'lying_leg_curls',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 30,
          restPeriodInSeconds: 30,
        },
        {
          id: 'lying_leg_curls',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 30,
          restPeriodInSeconds: 30,
        },
        {
          id: 'lying_leg_curls',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 30,
          restPeriodInSeconds: 30,
        },
        {
          id: 'lying_leg_curls',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 30,
          restPeriodInSeconds: 30,
        },
      ],
    },

    {
      id: 'core_strength',
      name: 'Core Strength',
      exercises: [
        {
          id: 'ab_crunch_machine',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 20,
          restPeriodInSeconds: 30,
        },
        {
          id: 'ab_crunch_machine',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 20,
          restPeriodInSeconds: 30,
        },
        {
          id: 'ab_crunch_machine',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 20,
          restPeriodInSeconds: 30,
        },
        {
          id: 'ab_crunch_machine',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 20,
          restPeriodInSeconds: 30,
        },
        {
          id: 'ab_crunch_machine',
          repsGoal: 10,
          repsAchieved: 10,
          autoIncrement: 2.5,
          weightInKilos: 20,
          restPeriodInSeconds: 30,
        },
      ],
    },

    {
      id: 'stretch',
      name: 'Stretch',
      exercises: [
        {
          id: 'left_leg_hamstring_stretch',
          timerInSeconds: 45,
        },
        {
          id: 'right_leg_hamstring_stretch',
          timerInSeconds: 45,
        },
        {
          id: 'left_glute_pigeon_pose_stretch',
          timerInSeconds: 45,
        },
        {
          id: 'right_glute_pigeon_pose_stretch',
          timerInSeconds: 45,
        },
        {
          id: 'kneeling_left_hip_flexor_stretch',
          timerInSeconds: 45,
        },
        {
          id: 'kneeling_right_hip_flexor_stretch',
          timerInSeconds: 45,
        },
        {
          id: 'overhead_band_chest_stretch',
          timerInSeconds: 45,
        },
      ],
    },
  ],
};

export default glutesAndGlory;
