import {Workout} from '../../reducers/workoutsReducer';
import {WORKOUT_VERSION} from '../../helpers/constants';
import Image from '../../assets/images/the-knees-over-toes-zero.jpg';

export const zero: Workout = {
  id: 'zero',
  name: 'Zero',
  description: 'Knee Ability Zero is Ben Patrick\'s (kneesovertoesguy) first and foundational program. It\'s a bodyweight rebuild from the ground up.',
  imageUrl: Image,
  version: WORKOUT_VERSION,
  exerciseGroups: [
    {
      id: 'e2ed380f-bf2e-4d67-9dfc-d176da1c5442',
      name: 'Zero',
      exercises: [
        {
          id: 'dea4e17a-f48b-4290-83c7-7d00cf12b576',
          exerciseId: 'tibialis_raise',
          name: 'Tibialis Raise',
          weightInKilos: 0,
          repsGoal: 25,
          repsAchieved: 25,
          autoIncrement: 0,
          restPeriodInSeconds: 90,
        },
        {
          id: '0be9228a-dee0-4564-94d0-045a1a8beeef',
          exerciseId: 'fhl_calf_raise',
          name: 'FHL Calf Raise',
          weightInKilos: 0,
          repsGoal: 25,
          repsAchieved: 25,
          autoIncrement: 0,
          restPeriodInSeconds: 90,
        },
        {
          id: '102de706-322f-43ec-8768-8bf31018aa80',
          exerciseId: 'kot_calf_raise',
          name: 'Knees Over Toes (KOT) Calf Raise',
          weightInKilos: 0,
          repsGoal: 25,
          repsAchieved: 25,
          autoIncrement: 0,
          restPeriodInSeconds: 90,
        },
        {
          id: '9a752ecf-0e70-41a5-a3f3-ba21b8aad81b',
          exerciseId: 'patrick_step',
          name: 'Patrick Step',
          weightInKilos: 0,
          repsGoal: 25,
          repsAchieved: 25,
          autoIncrement: 0,
          restPeriodInSeconds: 90,
        },
        {
          id: 'd0259eb0-31ec-4c3d-9d18-4776abf68591',
          exerciseId: 'atg_split_squat',
          name: 'ATG Split Squat (Set 1)',
          weightInKilos: 0,
          repsGoal: 5,
          repsAchieved: 5,
          autoIncrement: 0,
          restPeriodInSeconds: 90,
        },
        {
          id: 'b2399a1f-7343-4558-9059-4c4bc71d5058',
          exerciseId: 'atg_split_squat',
          name: 'ATG Split Squat (Set 2)',
          weightInKilos: 0,
          repsGoal: 5,
          repsAchieved: 5,
          autoIncrement: 0,
          restPeriodInSeconds: 90,
        },
        {
          id: '7743d191-78c9-4b6e-a487-ff5701d3ac2f',
          exerciseId: 'atg_split_squat',
          name: 'ATG Split Squat (Set 3)',
          weightInKilos: 0,
          repsGoal: 5,
          repsAchieved: 5,
          autoIncrement: 0,
          restPeriodInSeconds: 90,
        },
        {
          id: '24b22a03-ef51-40e0-9d81-14c12da60070',
          exerciseId: 'atg_split_squat',
          name: 'ATG Split Squat (Set 4)',
          weightInKilos: 0,
          repsGoal: 5,
          repsAchieved: 5,
          autoIncrement: 0,
          restPeriodInSeconds: 90,
        },
        {
          id: 'f55eedff-0ac9-4975-b062-00a6ac7333d5',
          exerciseId: 'atg_split_squat',
          name: 'ATG Split Squat (Set 5)',
          weightInKilos: 0,
          repsGoal: 5,
          repsAchieved: 5,
          autoIncrement: 0,
          restPeriodInSeconds: 90,
        },
        {
          id: 'f0e9f18b-2d25-496f-8683-e1bc981bb326',
          exerciseId: 'elephant_walk',
          name: 'Elephant Walk',
          weightInKilos: 0,
          repsGoal: 30,
          repsAchieved: 30,
          autoIncrement: 0,
          restPeriodInSeconds: 90,
        },
        {
          id: '5b5406d4-7711-42e9-8996-eb8434c66b5d',
          exerciseId: 'l_sit',
          name: 'L-Sit',
          timerInSeconds: 60,
          restPeriodInSeconds: 90,
        },
        {
          id: '900cf4ce-33d1-4252-a5c2-0dc07299e173',
          exerciseId: 'couch_stretch',
          name: 'Couch Stretch',
          timerInSeconds: 60,
          restPeriodInSeconds: 90,
        },
      ],
    },
  ],
};
